name: Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'BeatSyncConsole/**'
      - 'BeatSyncPlaylists/**'
      - 'BeatSyncLib/**'
      - 'Libs/**'
      - '.github/workflows/PublishBeatSyncConsole.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'BeatSyncConsole/**'
      - 'BeatSyncPlaylists/**'
      - 'BeatSyncLib/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build BeatSyncConsole/BeatSyncConsole.csproj --configuration Release
    - name: Publish_Win_x64
      id: publish-win64
      run: dotnet publish BeatSyncConsole/BeatSyncConsole.csproj --configuration Release /p:PublishProfile=win-x64
    - name: Publish_Linux_x64
      id: publish-linux64
      run: dotnet publish BeatSyncConsole/BeatSyncConsole.csproj --configuration Release /p:PublishProfile=linux-x64
    - name: Upload Win64 Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.publish-win64.outputs.filename }}
        path: ${{ steps.publish-win64.outputs.artifactpath }}
    - name: Make Executable
      run: chmod +x ${{ steps.publish-linux64.outputs.artifactpath }}/BeatSyncConsole/BeatSyncConsole
    - name: Upload Linux64 Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.publish-linux64.outputs.filename }}
        path: ${{ steps.publish-linux64.outputs.artifactpath }}

