name: Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'BeatSyncConsole/**'
      - 'BeatSyncPlaylists/**'
      - 'BeatSyncLib/**'
      - 'Libs/**'
      - '.github/workflows/PublishBeatSyncConsole.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'BeatSyncConsole/**'
      - 'BeatSyncPlaylists/**'
      - 'BeatSyncLib/**'
      - '.github/workflows/PublishBeatSyncConsole.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build BeatSyncConsole/BeatSyncConsole.csproj --configuration Release
    - name: Publish_Win_x64
      id: publish-win-x64
      run: dotnet publish BeatSyncConsole/BeatSyncConsole.csproj --configuration Release /p:PublishProfile=win-x64
    - name: Publish_Win_arm64
      id: publish-win-arm64
      run: dotnet publish BeatSyncConsole/BeatSyncConsole.csproj --configuration Release /p:PublishProfile=win-arm64
    - name: Publish_Linux_x64
      id: publish-linux64
      run: dotnet publish BeatSyncConsole/BeatSyncConsole.csproj --configuration Release /p:PublishProfile=linux-x64
    - name: Publish_Osx_x64
      id: publish-osx-x64
      run: dotnet publish BeatSyncConsole/BeatSyncConsole.csproj --configuration Release /p:PublishProfile=osx-x64
    - name: Publish_Osx_arm64
      id: publish-osx-arm64
      run: dotnet publish BeatSyncConsole/BeatSyncConsole.csproj --configuration Release /p:PublishProfile=osx-arm64
    - name: Upload Win-x64 Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.publish-win-x64.outputs.filename }}
        path: ${{ steps.publish-win-x64.outputs.artifactpath }}
    - name: Upload Win-arm64 Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.publish-win-arm64.outputs.filename }}
        path: ${{ steps.publish-win-arm64.outputs.artifactpath }}
    - name: Upload Osx_Arm64 Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.publish-osx-arm64.outputs.filename }}
        path: ${{ steps.publish-osx-arm64.outputs.artifactpath }}
    - name: Upload Osx_x64 Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.publish-osx-x64.outputs.filename }}
        path: ${{ steps.publish-osx-x64.outputs.artifactpath }}
    - name: Make Executable
      run: chmod -x ${{ steps.publish-linux64.outputs.artifactpath }}BeatSyncConsole/* ; chmod +x ${{ steps.publish-linux64.outputs.artifactpath }}BeatSyncConsole/BeatSyncConsole
    - name: Make Tar
      run: tar cvf -  ${{ steps.publish-linux64.outputs.artifactpath }} | gzip -9 - > ${{ steps.publish-linux64.outputs.artifactpath }}../${{ steps.publish-linux64.outputs.filename }}.tar.gz
    - name: Upload Linux64 Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.publish-linux64.outputs.filename }}
        path: ${{ steps.publish-linux64.outputs.artifactpath }}../${{ steps.publish-linux64.outputs.filename }}.tar.gz

